# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['posted_date'], 'verbose_name': '\u0417\u0430\u043c\u0435\u0442\u043a\u0430', 'verbose_name_plural': '\u0417\u0430\u043c\u0435\u0442\u043a\u0438'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
    ]
