# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-10 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181110_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='description',
        ),
    ]
